language: c

os: linux

install:

    - wget https://raw.githubusercontent.com/pelson/Obvious-CI/master/bootstrap-obvious-ci-and-miniconda.py
    - python bootstrap-obvious-ci-and-miniconda.py ~/miniconda x64 2 --without-obvci && source ~/miniconda/bin/activate root
    - conda config --set show_channel_urls True
    - conda install obvious-ci --yes -c conda-forge

script:

    - conda build vtk
